waypoint:
  dashboard:
    base-url: ${APP_BASE_URL}
    s3:
      bucket: ${S3_BUCKET}
      import-data-key-prefix: ${IMPORT_KEY_PREFIX}
      homework-response-key-prefix: ${HOMEWORK_RESPONSE_KEY_PREFIX}
      database-dump-prefix: ${DB_DUMP_KEY_PREFIX}
      step-attachment-key-prefix: ${STEP_ATTACHMENT_KEY_PREFIX}
    protocol-triggering:
      schedule: 0 0 0 * * *
    email-notification-queue-url: ${EMAIL_NOTIFICATION_QUEUE_URL}
management:
  endpoints:
    web:
      base-path: /
      exposure:
        #Endpoints need to be configured in WebSecurityConfiguration class
        include: health
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_API_ISSUER_URL}
  application:
    name: waypoint-dashboard-api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      poolName: Hikari
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  liquibase:
    enabled: true
  

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    liquibase: DEBUG
    org.springframework.security: INFO