waypoint:
  dashboard:
    base-url: http://host.docker.internal:8083
    s3:
      bucket: waypoints-dashboard-api
      import-data-key-prefix: import-data/
      homework-response-key-prefix: homework/
      database-dump-prefix: database-dump/
      step-attachment-key-prefix: step-attachments/
    protocol-triggering:
      schedule: 0 * * * * *

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8082
  application:
    name: waypoint-dashboard-api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://host.docker.internal:3306/dashboard?useSSL=false
    username: docker
    password:
    hikari:
      poolName: Hikari
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false


server:
  port: 8083

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web.servlet.mvc.method.annotation: INFO